apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
  namespace: default
  labels:
    app: application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: application
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: application-app
        image: sergey2410/application:latest
        securityContext:
          readOnlyRootFilesystem: true
        resources:
          requests: 
            memory: "256Mi"
            cpu: "250m"
          limits: 
            memory: "280Mi"
            cpu: "270m"
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: application
  namespace: default
spec:
  selector:
    app: application
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: application-pdb
  namespace: default
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: application
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: application-ingress
  namespace: default
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: application
                port:
                  number: 80
---
